### ISSUE TITLE
Feature Request: Pilot Name

### ISSUE THREAD

**Issue by brucesdad13** [nppc/Voltage_OSD#11]
Love this project! One idea occurred that perhaps, if it were possible to compile without the serial protocol, we could also have a compile-time option to include pilot name and/or target cursor on-screen.

**Comment by nppc** [comment]
Ok. Interesting idea.
Currently we use 1020 bytes of FLASH from 1024. So, no space for new features.
I tried to make conditional compilation without CONFIG feature.
Now we use only 582 bytes of FLASH from 1024. Seems plenty of space! :)

**Comment by nppc** [comment]
Alfa version of PILOTNAME feature is implemented. 
`Branch try_name`
I can't test it, because I have no spare pcbs (ordered more boards OshPark)...

**Comment by brucesdad13** [comment]
I will test ASAP! I have two PCBs left untouched of my original three. 😄Thanks again, Pavel!

**Comment by brucesdad13** [comment]
So far so good. Will build a PCB ASAP. 
![image](https://user-images.githubusercontent.com/23079971/29395709-e2cb4eb6-82e0-11e7-8d08-156ce2844a72.png)

**Comment by nppc** [comment]
Thank you.
I got PCBs and assembled one.
Tested... Doesn't work. Need to fix small bug...

**Comment by nppc** [comment]
Ok. Bug is fixed! :) Feel free to test working version... 
![image](https://raw.githubusercontent.com/nppc/B-uOSD/try_name/Images/PILOTNAME.png)

**Comment by nppc** [comment]
Implemented.
Draft in v1.3 (no official release), in v2.0 (will be released soon).
