### ISSUE TITLE
Bill of materials

### ISSUE THREAD

**Issue by brucesdad13** [nppc/Voltage_OSD#9]
Hello! Several of us would like to build one of these and have ordered PCBs from OSH Park. Can you offer a bill of materials of exactly which components we need? There's some confusion amongst us especially on the passives.

**Comment by nppc** [comment]
Ok, will add it to the Readme. Do you need some quick answer now?

**Comment by brucesdad13** [comment]
Yes a quick answer would be awesome. I'm on Mouser ordering components

**Comment by nppc** [comment]
Added BOM.txt to the root folder,
If you have any questions, ask here...

**Comment by nppc** [comment]
Added Mouser Part numbers

**Comment by brucesdad13** [comment]
Thank you! Will be building next week and maybe have a PR or two if any ideas come up 😄 Otherwise thank you again Pavel this looks like such a cool project. Which AIO are you using?

**Comment by nppc** [comment]
Thanks. :)
I tested it with this camera: https://www.banggood.com/Eachine-E010C-E010S-Spare-Part-p-1119217.html
But I think any camera will work. The simplicity of the schematic do not require to cut connectors on the camera. Just solder this B-uOSD to video pin.

**Comment by brucesdad13** [comment]
![image](https://user-images.githubusercontent.com/23079971/29255986-b263601a-8074-11e7-89cd-eb723b7127d4.png)

Looks ok? 😄 Will try flashing next.

**Comment by brucesdad13** [comment]
![image](https://user-images.githubusercontent.com/23079971/29258313-870a97f0-8086-11e7-92d8-595798ff124e.png)

It's alive! 😀

**Comment by nppc** [comment]
Ah, super! Looks nice. Congratulations! :) 
What camera and vtx are you using?

**Comment by brucesdad13** [comment]
This is the Boldclash F-02. It's a little on the heavy side but since comes already split it was the easiest to splice in the OSD. I ordered the exact camera you specified from banggood but it's on the slow boat. 😄 

![image](https://user-images.githubusercontent.com/23079971/29259436-fba43062-8090-11e7-991d-394b86b6280a.png)

**Comment by brucesdad13** [comment]
![assembled_top_side](https://user-images.githubusercontent.com/23079971/29259745-e0f3eba2-8092-11e7-9e4f-b376b18189bd.jpg)

**Comment by nppc** [comment]
Looks nice! How you solder? with solder station or somehow with reflow?

**Comment by brucesdad13** [comment]
By hand with a little Zeny hot air and solder 2-in-1 station. 😄 I have two more to build sometime this week. Next I want to look at the code and see... can we fit pilot name?

**Comment by brucesdad13** [comment]
Did some testing yesterday 😄 https://www.youtube.com/watch?v=hBjUEI953vA

**Comment by nppc** [comment]
Heh... If you will look to the code, then you will see, that we have only 4 bytes (2 instructions) left free in FLASH. :)
So, with current MCU (1KB of FLASH) to fit pilot name is not possible.
But you can do custom bitmap (8*10 pixels) and use it instead of copter bitmap.

And... WOW! I impressed that you did a video!!!
What do you think, can you give me the fragment of your video to post it in the readme here?

**Comment by brucesdad13** [comment]
I was wondering what if we removed the serial communications protocol and all the configuration was done compile-time? Yes I will happily give you the video clips.

**Comment by nppc** [comment]
OK, please, create new issue, and then I will look how much space we will gain and what we can do with it...

**Comment by brucesdad13** [comment]
Created 😄 It might be a bad idea on my part... Thanks Pavel!
